#!/bin/sh

set_wallpaper &
dwm_bar &
xcompmgr &
dunst &
xset r rate 300 50 &
sxhkd &
xmodmap ~/.config/xmodmap/Xmodmap &
unclutter &
probhat &
smartCaps &
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh
eval $(/usr/bin/gnome-keyring-daemon --start)
export SSH_AUTH_SOCK
mkdir -p "$HOME"/.local/share/keyrings



exec dwm > /dev/null 2>&1
